"""add date to vip

Revision ID: 116d4339383e
Revises: 175fef1bbf85
Create Date: 2024-12-17 22:30:55.847317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116d4339383e'
down_revision: Union[str, None] = '175fef1bbf85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vip_to', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vip_to')
    # ### end Alembic commands ###
