"""finish 1.1

Revision ID: 483eda45d6ee
Revises: b0e6a40c7e42
Create Date: 2024-12-20 20:59:15.564781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483eda45d6ee'
down_revision: Union[str, None] = 'b0e6a40c7e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alter_shop_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alter_shop_level')
    # ### end Alembic commands ###
