"""new fields

Revision ID: 03dcc9b7345f
Revises: 483eda45d6ee
Create Date: 2024-12-27 02:40:41.787119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dcc9b7345f'
down_revision: Union[str, None] = '483eda45d6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('group_link', sa.String(), nullable=False))
    op.add_column('products', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'products', ['chat_id'])
    op.drop_column('products', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'chat_id')
    op.drop_column('products', 'group_link')
    # ### end Alembic commands ###
