"""finish

Revision ID: ae62d46c2e25
Revises: 245c350b73d3
Create Date: 2024-12-19 19:40:55.878207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae62d46c2e25'
down_revision: Union[str, None] = '245c350b73d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'change_to_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('wifes', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wifes', sa.Column('sex', postgresql.ENUM('MALE', 'WOMEN', 'NOT_SETUP', name='sex'), autoincrement=False, nullable=False))
    op.alter_column('trades', 'change_to_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
