"""change fk

Revision ID: 498966d854d3
Revises: 116d4339383e
Create Date: 2024-12-18 02:57:32.191987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498966d854d3'
down_revision: Union[str, None] = '116d4339383e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slots_seller_id_fkey', 'slots', type_='foreignkey')
    op.create_foreign_key(None, 'slots', 'users', ['seller_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slots', type_='foreignkey')
    op.create_foreign_key('slots_seller_id_fkey', 'slots', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###
