"""new model

Revision ID: 1670b6340f8c
Revises: 6ac8608d429c
Create Date: 2024-12-16 09:41:02.973886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1670b6340f8c'
down_revision: Union[str, None] = '6ac8608d429c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('promo', sa.String(), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=25, scale=2), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocodes')
    # ### end Alembic commands ###
