"""finish 1.0

Revision ID: b0e6a40c7e42
Revises: ae62d46c2e25
Create Date: 2024-12-20 16:01:59.250789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e6a40c7e42'
down_revision: Union[str, None] = 'ae62d46c2e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=25, scale=2), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('alter_balance', sa.Numeric(precision=25, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alter_balance')
    op.drop_table('products')
    # ### end Alembic commands ###
