"""new trade model

Revision ID: cfd068bf6553
Revises: 166ac22fbadb
Create Date: 2024-12-29 03:54:09.512425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd068bf6553'
down_revision: Union[str, None] = '166ac22fbadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_shops',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wife_id', sa.BigInteger(), nullable=False),
    sa.Column('from_id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wife_id'], ['wifes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trades', sa.Column('trade_shop_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'trades', 'trade_shops', ['trade_shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'trade_shop_id')
    op.drop_table('trade_shops')
    # ### end Alembic commands ###
