services:
  db:
    image: postgres
    container_name: wife_db
    restart: on-failure
#    volumes:
#       - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  redis:
    build: 
      context: redis
      dockerfile: redis.dockerfile
    container_name: redis_cache
    restart: on-failure
#    volumes:
#       - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "root", "ping"]
      interval: 60s
      timeout: 5s
      retries: 3


  bot:
      build:
        context: .
      container_name: wife_bot
      env_file:
        - .env
      depends_on:
        - db
        - redis
      volumes:
        - .:/app


# volumes:
  # redis-data:
  # postgres-data:


